# Generated by Django 3.1.5 on 2022-01-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogMOdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=5000, null=True)),
                ('content', models.CharField(blank=True, max_length=500000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=5000, null=True)),
                ('email', models.CharField(blank=True, max_length=5000, null=True)),
                ('message', models.CharField(blank=True, max_length=50000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='urlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picurl', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
